language: java
jdk:
  - oraclejdk8
  - openjdk8

script:
  - mvn verify --settings .travis.settings.xml

deploy:
  provider: script
  script: mvn deploy --settings .travis.settings.xml
  skip_cleanup: true
